export default {
    'Learn to Fight Dirty' : {challenge: 'Street Fight', stage: 'early'},
    'Crush Your Rival': {challenge: 'Childhood Rival', stage: 'early'},
    'Resist Arrest': {challenge: 'Corrupt Official', stage: 'middle'},
    'Hide from the Fight': {challenge: 'Roving Bandits', stage: 'middle'},
    'Shatter the Sword': {challenge: 'Sword of Darkness', stage: 'late'},
    'Excel in Your Studies': {challenge: 'The Academy', stage: 'early'},
    'Learn Deep Lessons': {challenge: 'The Academy', stage: 'early'},
    'Plan the City\'s Defenses': {challenge: 'Plan for War', stage:'early'},
    'Build Fortifications': {challenge: 'Plan for War', stage:'early'},
    'Find a Lost Child': {challenge: 'Missing Person', stage: 'early'},
    'Climb to Safety': {challenge: 'Missing Person', stage: 'early'},
    'Arcane Ability': {challenge: 'Magical Test', stage: 'early'},
    'Sorcerous Talent': {challenge: 'Magical Test', stage: 'early'},
    'Train as a Spy': {challenge: 'Thieve\'s Guild', stage: 'early'},
    'Train as a Killer': {challenge: 'Thieve\'s Guild', stage: 'early'},
    'Enlist in the King\'s Army': {challenge: 'Call to Arms', stage: 'early'},
    'Defend Your Homestead': {challenge: 'Call to Arms', stage: 'early'},
    'Become a Brawler': {challenge: 'Street Fight', stage: 'early'},
    'Win a Foe\'s Loyalty': {challenge: 'Childhood Rival', stage: 'early'},
    'Heal the Wounded': {challenge: 'Raging Inferno', stage: 'early'},
    'Survive the Flames': {challenge: 'Raging Inferno', stage: 'early'},
    'Banish a Ghost': {challenge: 'Raging Inferno', stage: 'early'},
    'Gain a Spirit Guardian': {challenge: 'Raging Inferno', stage: 'early'},
    'Escape Your Pursuers':  {challenge: 'Lost in the Woods', stage: 'early'},
    'Find a Place of Power': {challenge: 'Lost in the Woods', stage: 'early'},
    'Uncover Hidden Lore': {challenge: 'Forbidden Lore', stage: 'early'},
    'Learn Dark Secrets': {challenge: 'Forbidden Lore', stage: 'early'},
    'Steal to Survive': {challenge: 'Cruel Winter', stage: 'early'},
    'Forage for Food': {challenge: 'Cruel Winter', stage: 'early'},
    'Harness Dark Power': {challenge: 'Dangerous Artifact', stage: 'early'},
    'Resist Temptation': {challenge: 'Dangerous Artifact', stage: 'early'},
    'Calm Your Attacker': {challenge: 'Armed Robbery', stage: 'early'},
    'Defend Your Family': {challenge: 'Armed Robbery', stage: 'early'},
    'Unlock a Secret Vault': {challenge: 'Vault of Secrets', stage: 'middle'},
    'Learn Forgotten Lore': {challenge: 'Vault of Secrets', stage: 'middle'},
    'Steal from the Rich': {challenge: 'Daring Heist', stage: 'middle'},
    'Give to the Poor': {challenge: 'Daring Heist', stage: 'middle'},
    'Lead an Attack': {challenge: 'Trench Warfare', stage: 'middle'},
    'Tend to the Injured': {challenge: 'Trench Warfare', stage: 'middle'},
    'Lead a Boarding Party': {challenge: 'Naval Battle', stage: 'middle'},
    'Sink the Enemy Ship': {challenge: 'Naval Battle', stage: 'middle'},
    'Pressed Into Service': {challenge: 'Captured', stage: 'middle'},
    'Break Out of Captivity': {challenge: 'Captured', stage: 'middle'},
    'Delve Into Darkness': {challenge: 'Perilous Dungeon', stage: 'middle'},
    'Escape With Treasure': {challenge: 'Perilous Dungeon', stage: 'middle'},
    'Solve a Mystery': {challenge: 'Murder Mystery', stage: 'middle'},
    'Conceal Your Crime': {challenge: 'Murder Mystery', stage: 'middle'},
    'Lead an Expedition': {challenge: 'Distant Lands', stage: 'middle'},
    'Discover the Unknown': {challenge: 'Distant Lands', stage: 'middle'},
    'Outwit a Gang Boss': {challenge: 'Street Gang', stage: 'middle'},
    'Take Over a Gang': {challenge: 'Street Gang', stage: 'middle'},
    'Pay a Bribe': {challenge: 'Corrupt Official', stage: 'middle'},
    'Repel a Bandit Attack': {challenge: 'Roving Bandits', stage: 'middle'},
    'Watch Over the City': {challenge: 'Guard Duty', stage: 'middle'},
    'Catch a Criminal': {challenge: 'Guard Duty', stage: 'middle'},
    'Survive a Harsh Journey': {challenge: 'Desert Caravan', stage: 'middle'},
    'Earn a Vast Fortune': {challenge: 'Desert Caravan', stage: 'middle'},
    'Climb the Summit': {challenge: 'Frozen Peak', stage: 'middle'},
    'Find Lost Wisdom': {challenge: 'Frozen Peak', stage: 'middle'},
    'Commune with Nature': {challenge: 'Savage Beast', stage: 'middle'},
    'Soothe a Savage Beast': {challenge: 'Savage Beast', stage: 'middle'},
    'Wield the Dark Blade': {challenge: 'Sword of Darkness', stage: 'late'},
    'Destroy the Assassins': {challenge: 'Assassin\'s Guild', stage: 'late'},
    'Take Over the Guild': {challenge: 'Assassin\'s Guild', stage: 'late'},
    'Drive Back a Demon Army': {challenge: 'Demon Horde', stage: 'late'},
    'Wield the Sun\'s light': {challenge: 'Demon Horde', stage: 'late'},
    'Duel the Enemy General': {challenge: 'Decisive Battle', stage: 'late'},
    'Sacrifice Your Army': {challenge: 'Decisive Battle', stage: 'late'},
    'Climb the Colossus': {challenge: 'Dark Colossus', stage: 'late'},
    'Bring Down the Giant': {challenge: 'Dark Colossus', stage: 'late'},
    'Win the Queen\'s Favor': {challenge: 'Queen\'s Chambers', stage: 'late'},
    'Unseat the Queen': {challenge: 'Queen\'s Chambers', stage: 'late'},
    'Champion of Light': {challenge: 'Divine Calling', stage: 'late'},
    'Servant of Darkness': {challenge: 'Divine Calling', stage: 'late'},
    'Journey to the Underworld': {challenge: 'Into the Abyss', stage: 'late'},
    'Rescue a Lost Love': {challenge: 'Into the Abyss', stage: 'late'},
    'Child of the Dark Lord': {challenge: 'Dark Revelation', stage: 'late'},
    'Tainted by Dark Magic': {challenge: 'Dark Revelation', stage: 'late'},
    'Pray for Deliverance': {challenge: 'Army of the Dead', stage: 'late'},
    'Survive the Horde': {challenge: 'Army of the Dead', stage: 'late'},
    'Enslave the Forest Spirit': {challenge: 'Force of Nature', stage: 'late'},
    'Restore the Balance': {challenge: 'Force of Nature', stage: 'late'},
    'Fight on the Front Lines': {challenge: 'Tryant\'s Army', stage: 'late'},
    'Lead the Rebels': {challenge: 'Tryant\'s Army', stage: 'late'},
    'Call for Mercy': {challenge: 'Heroic Rescue', stage: 'late'},
    'Save the Innocent': {challenge: 'Heroic Rescue', stage: 'late'},
    'Slay the Archmage': {challenge: 'Trial of the Mage', stage: 'late'},
    'Become the Archmage': {challenge: 'Trial of the Mage', stage: 'late'},
    'Succumb to Dark Magic': {challenge: 'Witch\'s Den', stage: 'late'},
    'Defeat a Witch': {challenge: 'Witch\'s Den', stage: 'late'},
    'Banish the Fiend': {challenge: 'Ancient Evil', stage: 'late'},
    'Bargain for Power': {challenge: 'Ancient Evil', stage: 'late'},
    'Extinguish the Fire': {challenge: 'Rogue Elemental', stage: 'late'},
    'Harness Living Flame': {challenge: 'Rogue Elemental', stage: 'late'},
    'Steal the Treasure': {challenge: 'Dragon\'s Horde', stage: 'late'},
    'Slay the Dragon': {challenge: 'Dragon\'s Horde', stage: 'late'},
    'Advice the King': {challenge: 'King\'s Council', stage: 'late'},
    'Claim the Crown': {challenge: 'King\'s Council', stage: 'late'},
    'Disarm Deadly Traps': {challenge: 'Crypt of Horrors', stage: 'late'},
    'Destroy the Demilich': {challenge: 'Crypt of Horrors', stage: 'late'},
    'Plot Your Revenge': {challenge: 'Imprisoned', stage: 'late'},
    'Escape to Freedom': {challenge: 'Imprisoned', stage: 'late'},
}