export default [
    'Sailor',
    'Student',
    'Beggar',
    'Noble',
    'Performer',
    'Squire',
    'Farmer',
    'Apprentice',
    'Merchant',
    'Conscript',
    'Acolyte',
    'Hunter',
    'Outlander',
    'Settler',
    'Pickpocket',
] as const